services:
    app:
        build:
            context: .
        ports:
            - "5678:5678" # Expose the debug port
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
